### ISSUE TITLE
AnimatedMorphCube.gltf is not displayed in WebGL environment

### ISSUE THREAD

**Issue by cx20** [google/filament#1761]
**Describe the bug**
I tried to display [AnimatedMorphCube.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AnimatedMorphCube) with the WebGL version of Filament.
However, the warning was output to the browser console and the model was not displayed.

**To Reproduce**
[AnimatedMorphCube.gltf + Filament result:](https://rawcdn.githack.com/cx20/gltf-test/c283ae4d6a220b40dea64a2bc44938f40e02bb3e/examples/filament/index.html?category=tutorialModels&model=SimpleMorph&scale=1&type=glTF)
```
GL_INVALID_OPERATION: Vertex shader input type does not match the type of the bound vertex attribute.
```

**Expected behavior**
![screenshot](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/AnimatedMorphCube/screenshot/screenshot.gif?raw=true)

**Desktop (please complete the following information):**
 - OS: Windows 10 + Chrome 77
 - GPU: Intel HD Graphics 520
 - Backend: WebGL/ANGLE (Intel(R) HD Graphics 520 Direct3D11 vs_5_0 ps_5_0)

**Comment by prideout** [comment]
Interesting, thanks.  I'm surprised this wasn't fixed by 2a8ecd2b59e6bdf20425f5f5e85aa504bd70ffe5.

**Comment by cx20** [comment]
When I tried it with Firefox, the content of the warning was the following message.
```
Error: WebGL warning: drawElements: Vertex attrib 5 requires data of type UINT, but is being supplied with type FLOAT.
```

**Comment by prideout** [comment]
Yes this issue is basically a dup of #1726, which should have been fixed.  Can you confirm that you have the fix noted in my previous comment?

**Comment by elalish** [comment]
#1726 has also not been fixed, as I'm still getting the same errors as well for all glTFs with morph targets.

**Comment by prideout** [comment]
Fixed for reals with 3c6f3e7787bd2f89d4d41cb0988af84c4a13baa2.

**Comment by cx20** [comment]
I tried the latest version of filament and it seems that there is a build error.
![image](https://user-images.githubusercontent.com/1833979/68019822-211e0480-fce0-11e9-95f8-58945061c653.png)

https://source.cloud.google.com/results/invocations/39851f01-7dfd-401b-b01e-2dafef41ac8c/log

**Comment by cx20** [comment]
I have confirmed that this model can be displayed with the latest version of Filament.
[AnimatedMorphCube.gltf + Filament result:](https://rawcdn.githack.com/cx20/gltf-test/0255307988ab942eba9b5ab768c65fd1e82fef61/examples/filament/index.html?category=tutorialModels&model=AnimatedMorphCube&scale=1&type=glTF)

![image](https://user-images.githubusercontent.com/1833979/68063468-99bea880-fd54-11e9-9fbc-43b655b25a44.png)

I updated the status of [gltf-test](https://github.com/cx20/gltf-test). I think that almost all models that do not use the extension feature can be displayed.

https://github.com/cx20/gltf-test#simple-models-for-testing-individual-features
![image](https://user-images.githubusercontent.com/1833979/68063844-a55f9e80-fd57-11e9-9929-dba4a7421c83.png)
