### ISSUE TITLE
ubuntu 20.04 problem with compilation

### ISSUE THREAD

**Issue by femust** [google/filament#2617]
**Describe the bug**
So I compile, and I have the following:

```
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libc++.a(algorithm.cpp.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libc++.a(hash.cpp.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libc++.a(ios.cpp.o): relocation R_X86_64_32S against symbol `_ZTVNSt3__18ios_baseE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libc++.a(iostream.cpp.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libc++.a(locale.cpp.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libc++.a(memory.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libc++.a(mutex.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libc++.a(new.cpp.o): relocation R_X86_64_32 against symbol `_ZTISt9bad_alloc' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libc++.a(stdexcept.cpp.o): relocation R_X86_64_32S against symbol `_ZTVSt11logic_error' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libc++.a(string.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libc++.a(system_error.cpp.o): relocation R_X86_64_32S against symbol `_ZTVNSt3__114error_categoryE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libc++.a(vector.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libc++.a(charconv.cpp.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libc++.a(condition_variable.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libc++.a(exception.cpp.o): relocation R_X86_64_32S against symbol `_ZTVSt16nested_exception' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libc++.a(thread.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libc++.a(future.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [third_party/spirv-tools/source/CMakeFiles/SPIRV-Tools-shared.dir/build.make:1081: third_party/spirv-tools/source/libSPIRV-Tools-shared.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:3796: third_party/spirv-tools/source/CMakeFiles/SPIRV-Tools-shared.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

```
After this:

```
cmake -DCMAKE_CXX_FLAGS="-fPIC" -DCMAKE_C_FLAGS="-fPIC" ..
make
```

and still the same error

**To Reproduce**
git clone repo ...

**Expected behavior**
Compiled repo

**Desktop (please complete the following information):**
 - OS: Linux (ubuntu 20.04)
 - GPU:  NVIDIA RTX 2080

**Comment by unicomp21** [comment]
I don't think anyone has tried building on ubuntu 20.04 yet.  Here is my Dockerfile for 18.04

Maybe w/ a few tweaks we can make it run for 20.04 as well?  Wish I could be more helpful.

https://gist.github.com/unicomp21/047236ec0526ba65d65f8c11d4864393

**Comment by femust** [comment]
@unicomp21  thanks for your reply. Sometimes when I play around with compilers, I have something like:

`(CubemapUtils.cpp.o): in function `filament::ibl::CubemapUtils::solidAngle(unsigned long, unsigned long, unsigned long)':
CubemapUtils.cpp:(.text._ZN8filament3ibl12CubemapUtils10solidAngleEmmm+0x132): undefined reference to `__atan2f_finite'
/usr/bin/ld: CubemapUtils.cpp:(.text._ZN8filament3ibl12CubemapUtils10solidAngleEmmm+0x197): undefined reference to `__atan2f_finite'
/usr/bin/ld: CubemapUtils.cpp:(.text._ZN8filament3ibl12CubemapUtils10solidAngleEmmm+0x20c): undefined reference to `__atan2f_finite'
/usr/bin/ld: CubemapUtils.cpp:(.text._ZN8filament3ibl12CubemapUtils10solidAngleEmmm+0x26c): undefined reference to `__atan2f_finite'
/usr/bin/ld: /home/andrzej/Libraries/Open3D/build/3rdparty_install/lib/libibl.a(CubemapUtils.cpp.o): in function `std::__1::__function::__func<filament::ibl::CubemapUtils::equirectangularToCubemap(utils::JobSystem&, filament::ibl::Cubemap&, filament::ibl::Image const&)::$_2, std::__1::allocator<filament::ibl::CubemapUtils::equirectangularToCubemap(utils::JobSystem&, filament::ibl::Cubemap&, filament::ibl::Image const&)::$_2>, void (filament::ibl::CubemapUtils::EmptyState&, unsigned long, filament::ibl::Cubemap::Face, filament::math::details::TVec3<float>*, unsigned long)>::operator()(filament::ibl::CubemapUtils::EmptyState&, unsigned long&&, filament::ibl::Cubemap::Face&&, filament::math::details::TVec3<float>*&&, unsigned long&&)':
CubemapUtils.cpp:(.text._ZNSt3__110__function6__funcIZN8filament3ibl12CubemapUtils24equirectangularToCubemapERN5utils9JobSystemERNS3_7CubemapERKNS3_5ImageEE3$_2NS_9allocatorISD_EEFvRNS4_10EmptyStateEmNS8_4FaceEPNS2_4math7details5TVec3IfEEmEEclESH_OmOSI_OSN_SQ_+0x247): undefined reference to `__atan2f_finite'
/usr/bin/ld: CubemapUtils.cpp:(.text._ZNSt3__110__function6__funcIZN8filament3ibl12CubemapUtils24equirectangularToCubemapERN5utils9JobSystemERNS3_7CubemapERKNS3_5ImageEE3$_2NS_9allocatorISD_EEFvRNS4_10EmptyStateEmNS8_4FaceEPNS2_4math7details5TVec3IfEEmEEclESH_OmOSI_OSN_SQ_+0x25b): undefined reference to `__asinf_finite'
/usr/bin/ld: CubemapUtils.cpp:(.text._ZNSt3__110__function6__funcIZN8filament3ibl12CubemapUtils24equirectangularToCubemapERN5utils9JobSystemERNS3_7CubemapERKNS3_5ImageEE3$_2NS_9allocatorISD_EEFvRNS4_10EmptyStateEmNS8_4FaceEPNS2_4math7details5TVec3IfEEmEEclESH_OmOSI_OSN_SQ_+0x46e): undefined reference to `__atan2f_finite'
/usr/bin/ld: CubemapUtils.cpp:(.text._ZNSt3__110__function6__funcIZN8filament3ibl12CubemapUtils24equirectangularToCubemapERN5utils9JobSystemERNS3_7CubemapERKNS3_5ImageEE3$_2NS_9allocatorISD_EEFvRNS4_10EmptyStateEmNS8_4FaceEPNS2_4math7details5TVec3IfEEmEEclESH_OmOSI_OSN_SQ_+0x491): undefined reference to `__asinf_finite'
/usr/bin/ld: CubemapUtils.cpp:(.text._ZNSt3__110__function6__funcIZN8filament3ibl12CubemapUtils24equirectangularToCubemapERN5utils9JobSystemERNS3_7CubemapERKNS3_5ImageEE3$_2NS_9allocatorISD_EEFvRNS4_10EmptyStateEmNS8_4FaceEPNS2_4math7details5TVec3IfEEmEEclESH_OmOSI_OSN_SQ_+0x62d): undefined reference to `__atan2f_finite'
/usr/bin/ld: CubemapUtils.cpp:(.text._ZNSt3__110__function6__funcIZN8filament3ibl12CubemapUtils24equirectangularToCubemapERN5utils9JobSystemERNS3_7CubemapERKNS3_5ImageEE3$_2NS_9allocatorISD_EEFvRNS4_10EmptyStateEmNS8_4FaceEPNS2_4math7details5TVec3IfEEmEEclESH_OmOSI_OSN_SQ_+0x650): undefined reference to `__asinf_finite'
/usr/bin/ld: CubemapUtils.cpp:(.text._ZNSt3__110__function6__funcIZN8filament3ibl12CubemapUtils24equirectangularToCubemapERN5utils9JobSystemERNS3_7CubemapERKNS3_5ImageEE3$_2NS_9allocatorISD_EEFvRNS4_10EmptyStateEmNS8_4FaceEPNS2_4math7details5TVec3IfEEmEEclESH_OmOSI_OSN_SQ_+0x7b3): undefined reference to `__atan2f_finite'
/usr/bin/ld: CubemapUtils.cpp:(.text._ZNSt3__110__function6__funcIZN8filament3ibl12CubemapUtils24equirectangularToCubemapERN5utils9JobSystemERNS3_7CubemapERKNS3_5ImageEE3$_2NS_9allocatorISD_EEFvRNS4_10EmptyStateEmNS8_4FaceEPNS2_4math7details5TVec3IfEEmEEclESH_OmOSI_OSN_SQ_+0x7d6): undefined reference to `__asinf_finite'
/usr/bin/ld: CubemapUtils.cpp:(.text._ZNSt3__110__function6__funcIZN8filament3ibl12CubemapUtils24equirectangularToCubemapERN5utils9JobSystemERNS3_7CubemapERKNS3_5ImageEE3$_2NS_9allocatorISD_EEFvRNS4_10EmptyStateEmNS8_4FaceEPNS2_4math7details5TVec3IfEEmEEclESH_OmOSI_OSN_SQ_+0xa52): undefined reference to `__atan2f_finite'
/usr/bin/ld: CubemapUtils.cpp:(.text._ZNSt3__110__function6__funcIZN8filament3ibl12CubemapUtils24equirectangularToCubemapERN5utils9JobSystemERNS3_7CubemapERKNS3_5ImageEE3$_2NS_9allocatorISD_EEFvRNS4_10EmptyStateEmNS8_4FaceEPNS2_4math7details5TVec3IfEEmEEclESH_OmOSI_OSN_SQ_+0xa73): undefined reference to `__asinf_finite'
/usr/bin/ld: CubemapUtils.cpp:(.text._ZNSt3__110__function6__funcIZN8filament3ibl12CubemapUtils24equirectangularToCubemapERN5utils9JobSystemERNS3_7CubemapERKNS3_5ImageEE3$_2NS_9allocatorISD_EEFvRNS4_10EmptyStateEmNS8_4FaceEPNS2_4math7details5TVec3IfEEmEEclESH_OmOSI_OSN_SQ_+0xc51): undefined reference to `__atan2f_finite'
/usr/bin/ld: CubemapUtils.cpp:(.text._ZNSt3__110__function6__funcIZN8filament3ibl12CubemapUtils24equirectangularToCubemapERN5utils9JobSystemERNS3_7CubemapERKNS3_5ImageEE3$_2NS_9allocatorISD_EEFvRNS4_10EmptyStateEmNS8_4FaceEPNS2_4math7details5TVec3IfEEmEEclESH_OmOSI_OSN_SQ_+0xc71): undefined reference to `__asinf_finite'
/usr/bin/ld: CubemapUtils.cpp:(.text._ZNSt3__110__function6__funcIZN8filament3ibl12CubemapUtils24equirectangularToCubemapERN5utils9JobSystemERNS3_7CubemapERKNS3_5ImageEE3$_2NS_9allocatorISD_EEFvRNS4_10EmptyStateEmNS8_4FaceEPNS2_4math7details5TVec3IfEEmEEclESH_OmOSI_OSN_SQ_+0xe28): undefined reference to `__atan2f_finite'
/usr/bin/ld: CubemapUtils.cpp:(.text._ZNSt3__110__function6__funcIZN8filament3ibl12CubemapUtils24equirectangularToCubemapERN5utils9JobSystemERNS3_7CubemapERKNS3_5ImageEE3$_2NS_9allocatorISD_EEFvRNS4_10EmptyStateEmNS8_4FaceEPNS2_4math7details5TVec3IfEEmEEclESH_OmOSI_OSN_SQ_+0xe49): undefined reference to `__asinf_finite'
/usr/bin/ld: CubemapUtils.cpp:(.text._ZNSt3__110__function6__funcIZN8filament3ibl12CubemapUtils24equirectangularToCubemapERN5utils9JobSystemERNS3_7CubemapERKNS3_5ImageEE3$_2NS_9allocatorISD_EEFvRNS4_10EmptyStateEmNS8_4FaceEPNS2_4math7details5TVec3IfEEmEEclESH_OmOSI_OSN_SQ_+0x1078): undefined reference to `__atan2f_finite'
/usr/bin/ld: CubemapUtils.cpp:(.text._ZNSt3__110__function6__funcIZN8filament3ibl12CubemapUtils24equirectangularToCubemapERN5utils9JobSystemERNS3_7CubemapERKNS3_5ImageEE3$_2NS_9allocatorISD_EEFvRNS4_10EmptyStateEmNS8_4FaceEPNS2_4math7details5TVec3IfEEmEEclESH_OmOSI_OSN_SQ_+0x1098): undefined reference to `__asinf_finite'
/usr/bin/ld: CubemapUtils.cpp:(.text._ZNSt3__110__function6__funcIZN8filament3ibl12CubemapUtils24equirectangularToCubemapERN5utils9JobSystemERNS3_7CubemapERKNS3_5ImageEE3$_2NS_9allocatorISD_EEFvRNS4_10EmptyStateEmNS8_4FaceEPNS2_4math7details5TVec3IfEEmEEclESH_OmOSI_OSN_SQ_+0x1278): undefined reference to `__atan2f_finite'
/usr/bin/ld: CubemapUtils.cpp:(.text._ZNSt3__110__function6__funcIZN8filament3ibl12CubemapUtils24equirectangularToCubemapERN5utils9JobSystemERNS3_7CubemapERKNS3_5ImageEE3$_2NS_9allocatorISD_EEFvRNS4_10EmptyStateEmNS8_4FaceEPNS2_4math7details5TVec3IfEEmEEclESH_OmOSI_OSN_SQ_+0x1299): undefined reference to `__asinf_finite'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

maybe this is easier to solve?

**Comment by unicomp21** [comment]
FROM ubuntu:20.04

RUN apt-get update

RUN apt-get install -y cmake ninja-build python3-distutils
RUN apt-get install -y clang-9 libglu1-mesa-dev libc++-9-dev libc++abi-9-dev
RUN apt-get install -y libxi-dev
RUN apt-get install -y emacs-nox git curl wget unzip

RUN update-alternatives --install /usr/bin/clang clang /usr/bin/clang-9 100
RUN update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-9 100
RUN update-alternatives --install /usr/bin/cc cc /usr/bin/clang 100
RUN update-alternatives --install /usr/bin/c++ c++ /usr/bin/clang++ 100

WORKDIR /tmp
RUN git clone https://github.com/emscripten-core/emsdk.git
WORKDIR /tmp/emsdk
RUN /bin/bash -c "source ./emsdk_env.sh"

ENV PATH="/tmp/emsdk:/tmp/emsdk/upstream/emscripten:/tmp/emsdk/node/12.9.1_64bit/bin:${PATH}"

ENV EMSDK /tmp/emsdk
ENV EM_CONFIG /root/.emscripten
ENV EMSDK_NODE /tmp/emsdk/node/12.9.1_64bit/bin/node
RUN ./emsdk install latest
RUN ./emsdk activate latest

WORKDIR /tmp
RUN git clone https://github.com/google/filament.git

WORKDIR /tmp/filament
RUN ./build.sh -p webgl release

**Comment by unicomp21** [comment]
The above err's out on spirvXXX stuff, I'm clearly out of my depth now.

**Comment by kpeeters** [comment]
@femust Your 2nd set of errors is similar to https://github.com/google/filament/issues/2146; that's a different thing probably.

**Comment by femust** [comment]
@kpeeters  I tried this, but for me, it didn't work, unfortunately...

**Comment by kpeeters** [comment]
I think the issue is that you cannot produce a *shared* library by linking it with a *static* one. The static one in this case is `libc++.a`. The shared library you are trying to build is `libSPIRV-Tools-shared.so`. That will not fly. You would need to rebuild `libc++.a` with `-fPIC`.

**Comment by bejado** [comment]
We turn `fpic` on in several places ([here](https://github.com/google/filament/blob/master/filament/CMakeLists.txt#L340-L342) for example) when building for Linux. Maybe we shouldn't be doing this unconditionally?

Can you post the SPIRV errors you're seeing?

**Comment by primodial-void** [comment]
Any update here? same issue -> `FAILED: third_party/spirv-tools/source/libSPIRV-Tools-shared.so 
`

**Comment by bejado** [comment]
I don't even think we need `libSPIRV-Tools-shared` anywhere in Filament. Can you try re-building with the  [bjd/spirv-tools-shared](https://github.com/google/filament/tree/bjd/spirv-tools-shared) branch?

**Comment by primodial-void** [comment]
Yeah, that works well. It seems that SPIRV Tools shared library creates issues and removing it does the job.

**Comment by bejado** [comment]
Great, this should be fixed on main then.

**Comment by wumo** [comment]
Still can't compile because of `third_party/spirv-tools/source/libSPIRV-Tools-shared.so ` on `main` branch.

**Comment by bejado** [comment]
Looks like `libSPIRV-Tools-shared.so` was reintroduced during a spirv-tools upgrade. I'll update it on main again.

**Comment by wumo** [comment]
@bejado Thanks, it now compiles without `libSPIRV-Tools-shared.so`. But still I can't compile the java bindings because of the same reason like `libSPIRV-Tools-shared.so`. The error log shows `xxx libc++.a xxx recompile with -fPIC`
```
[238/304] Linking CXX shared library java/filament/libfilament-jni.so
FAILED: java/filament/libfilament-jni.so 
: && /usr/bin/clang++-10 -fPIC -std=c++17 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -stdlib=libc++ -fPIC -fcolor-diagnostics -DTNT_DEV -g -fstack-protector  -Wl,--gc-sections -Wl,-Bsymbolic-functions -shared -Wl,-soname,libfilament-jni.so -o java/filament/libfilament-jni.so java/filament/CMakeFiles/filament-jni.dir/__/__/android/filament-android/src/main/cpp/Camera.cpp.o java/filament/CMakeFiles/filament-jni.dir/__/__/android/filament-android/src/main/cpp/Colors.cpp.o java/filament/CMakeFiles/filament-jni.dir/__/__/android/filament-android/src/main/cpp/ColorGrading.cpp.o java/filament/CMakeFiles/filament-jni.dir/__/__/android/filament-android/src/main/cpp/VertexBuffer.cpp.o java/filament/CMakeFiles/filament-jni.dir/__/__/android/filament-android/src/main/cpp/Engine.cpp.o java/filament/CMakeFiles/filament-jni.dir/__/__/android/filament-android/src/main/cpp/EntityManager.cpp.o java/filament/CMakeFiles/filament-jni.dir/__/__/android/filament-android/src/main/cpp/Fence.cpp.o java/filament/CMakeFiles/filament-jni.dir/__/__/android/filament-android/src/main/cpp/IndexBuffer.cpp.o java/filament/CMakeFiles/filament-jni.dir/__/__/android/filament-android/src/main/cpp/IndirectLight.cpp.o java/filament/CMakeFiles/filament-jni.dir/__/__/android/filament-android/src/main/cpp/LightManager.cpp.o java/filament/CMakeFiles/filament-jni.dir/__/__/android/filament-android/src/main/cpp/Material.cpp.o java/filament/CMakeFiles/filament-jni.dir/__/__/android/filament-android/src/main/cpp/MaterialInstance.cpp.o java/filament/CMakeFiles/filament-jni.dir/__/__/android/filament-android/src/main/cpp/MathUtils.cpp.o java/filament/CMakeFiles/filament-jni.dir/__/__/android/filament-android/src/main/cpp/NativeSurface.cpp.o java/filament/CMakeFiles/filament-jni.dir/__/__/android/filament-android/src/main/cpp/RenderableManager.cpp.o java/filament/CMakeFiles/filament-jni.dir/__/__/android/filament-android/src/main/cpp/Renderer.cpp.o java/filament/CMakeFiles/filament-jni.dir/__/__/android/filament-android/src/main/cpp/RenderTarget.cpp.o java/filament/CMakeFiles/filament-jni.dir/__/__/android/filament-android/src/main/cpp/Scene.cpp.o java/filament/CMakeFiles/filament-jni.dir/__/__/android/filament-android/src/main/cpp/SkyBox.cpp.o java/filament/CMakeFiles/filament-jni.dir/__/__/android/filament-android/src/main/cpp/Stream.cpp.o java/filament/CMakeFiles/filament-jni.dir/__/__/android/filament-android/src/main/cpp/Texture.cpp.o java/filament/CMakeFiles/filament-jni.dir/__/__/android/filament-android/src/main/cpp/TextureSampler.cpp.o java/filament/CMakeFiles/filament-jni.dir/__/__/android/filament-android/src/main/cpp/TransformManager.cpp.o java/filament/CMakeFiles/filament-jni.dir/__/__/android/filament-android/src/main/cpp/View.cpp.o java/filament/CMakeFiles/filament-jni.dir/__/__/android/filament-android/src/main/cpp/Filament.cpp.o java/filament/CMakeFiles/filament-jni.dir/__/__/android/filament-android/src/main/cpp/nativewindow/JAWTUtils.cpp.o java/filament/CMakeFiles/filament-jni.dir/__/__/android/common/CallbackUtils.cpp.o java/filament/CMakeFiles/filament-jni.dir/__/__/android/common/NioUtils.cpp.o java/filament/CMakeFiles/filament-jni.dir/__/__/android/filament-android/src/main/cpp/nativewindow/Linux.cpp.o  -Wl,-rpath,/home/wumo/.jdks/openjdk-14.0.2/lib:  -static-libgcc -static-libstdc++  -Wl,-Bstatic  -lc++  -lc++abi  filament/libfilament.a  -Wl,-Bdynamic  /home/wumo/.jdks/openjdk-14.0.2/lib/libjawt.so  filament/backend/libbackend.a  libs/bluegl/libbluegl.a  libs/bluevk/libbluevk.a  libs/geometry/libgeometry.a  libs/ibl/libibl-lite.a  libs/matdbg/libmatdbg.a  libs/filaflat/libfilaflat.a  third_party/smol-v/tnt/libsmol-v.a  libs/filabridge/libfilabridge.a  libs/math/libmath.a  libs/utils/libutils.a  third_party/civetweb/tnt/libcivetweb.a  third_party/glslang/tnt/SPIRV/libSPIRV.a  third_party/glslang/tnt/glslang/libglslang.a  third_party/glslang/tnt/OGLCompilersDLL/libOGLCompiler.a  third_party/glslang/tnt/glslang/OSDependent/Unix/libOSDependent.a  -pthread  third_party/spirv-tools/source/libSPIRV-Tools.a  /usr/lib/x86_64-linux-gnu/librt.so  third_party/spirv-cross/tnt/libspirv-cross-glsl.a  third_party/spirv-cross/tnt/libspirv-cross-msl.a  third_party/spirv-cross/tnt/libspirv-cross-core.a  libs/matdbg/libmatdbg_resources.a  -static-libgcc -static-libstdc++  -Wl,-Bstatic  -lc++  -lc++abi  -Wl,-Bdynamic  -ldl && :
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(new.cpp.o): relocation R_X86_64_32 against symbol `_ZTISt9bad_alloc' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(stdexcept.cpp.o): relocation R_X86_64_32S against symbol `_ZTVSt11logic_error' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(vector.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(algorithm.cpp.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(chrono.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(hash.cpp.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(ios.cpp.o): relocation R_X86_64_32S against symbol `_ZTVNSt3__18ios_baseE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(iostream.cpp.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(locale.cpp.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(memory.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(mutex.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(random.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(string.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(system_error.cpp.o): relocation R_X86_64_32S against symbol `_ZTVNSt3__114error_categoryE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(thread.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(charconv.cpp.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(condition_variable.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(exception.cpp.o): relocation R_X86_64_32S against symbol `_ZTVSt16nested_exception' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(future.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[241/304] Linking CXX shared library java/gltfio/libgltfio-jni.so
FAILED: java/gltfio/libgltfio-jni.so 
: && /usr/bin/clang++-10 -fPIC -std=c++17 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -stdlib=libc++ -fPIC -fcolor-diagnostics -DTNT_DEV -g -fstack-protector  -Wl,--gc-sections -Wl,-Bsymbolic-functions -shared -Wl,-soname,libgltfio-jni.so -o java/gltfio/libgltfio-jni.so java/gltfio/CMakeFiles/gltfio-jni.dir/__/__/android/gltfio-android/src/main/cpp/Animator.cpp.o java/gltfio/CMakeFiles/gltfio-jni.dir/__/__/android/gltfio-android/src/main/cpp/AssetLoader.cpp.o java/gltfio/CMakeFiles/gltfio-jni.dir/__/__/android/gltfio-android/src/main/cpp/FilamentAsset.cpp.o java/gltfio/CMakeFiles/gltfio-jni.dir/__/__/android/gltfio-android/src/main/cpp/FilamentInstance.cpp.o java/gltfio/CMakeFiles/gltfio-jni.dir/__/__/android/gltfio-android/src/main/cpp/MaterialProvider.cpp.o java/gltfio/CMakeFiles/gltfio-jni.dir/__/__/android/gltfio-android/src/main/cpp/ResourceLoader.cpp.o java/gltfio/CMakeFiles/gltfio-jni.dir/__/__/android/common/CallbackUtils.cpp.o java/gltfio/CMakeFiles/gltfio-jni.dir/__/__/android/common/NioUtils.cpp.o  -static-libgcc -static-libstdc++  -Wl,-Bstatic  -lc++  -lc++abi  libs/gltfio/libgltfio_core.a  libs/gltfio/libgltfio_resources.a  filament/libfilament.a  filament/backend/libbackend.a  libs/bluegl/libbluegl.a  libs/bluevk/libbluevk.a  libs/ibl/libibl-lite.a  libs/matdbg/libmatdbg.a  libs/filaflat/libfilaflat.a  third_party/smol-v/tnt/libsmol-v.a  libs/filabridge/libfilabridge.a  third_party/civetweb/tnt/libcivetweb.a  third_party/glslang/tnt/SPIRV/libSPIRV.a  third_party/glslang/tnt/glslang/libglslang.a  third_party/glslang/tnt/OGLCompilersDLL/libOGLCompiler.a  third_party/glslang/tnt/glslang/OSDependent/Unix/libOSDependent.a  third_party/spirv-tools/source/libSPIRV-Tools.a  -Wl,-Bdynamic  /usr/lib/x86_64-linux-gnu/librt.so  third_party/spirv-cross/tnt/libspirv-cross-glsl.a  third_party/spirv-cross/tnt/libspirv-cross-msl.a  third_party/spirv-cross/tnt/libspirv-cross-core.a  libs/matdbg/libmatdbg_resources.a  -ldl  libs/geometry/libgeometry.a  libs/math/libmath.a  libs/utils/libutils.a  -pthread  third_party/draco/tnt/libdracodec.a  -static-libgcc -static-libstdc++  -Wl,-Bstatic  -lc++  -lc++abi  -Wl,-Bdynamic && :
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(new.cpp.o): relocation R_X86_64_32 against symbol `_ZTISt9bad_alloc' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(algorithm.cpp.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(chrono.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(hash.cpp.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(ios.cpp.o): relocation R_X86_64_32S against symbol `_ZTVNSt3__18ios_baseE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(iostream.cpp.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(locale.cpp.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(memory.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(mutex.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(random.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(stdexcept.cpp.o): relocation R_X86_64_32S against symbol `_ZTVSt11logic_error' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(string.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(system_error.cpp.o): relocation R_X86_64_32S against symbol `_ZTVNSt3__114error_categoryE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(thread.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(vector.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(charconv.cpp.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(condition_variable.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(exception.cpp.o): relocation R_X86_64_32S against symbol `_ZTVSt16nested_exception' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(future.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[244/304] Linking CXX shared library java/filamat/libfilamat-jni.so
FAILED: java/filamat/libfilamat-jni.so 
: && /usr/bin/clang++-10 -fPIC -std=c++17 -fstrict-aliasing -Wno-unknown-pragmas -Wno-unused-function -stdlib=libc++ -fPIC -fcolor-diagnostics -DTNT_DEV -g -fstack-protector  -Wl,--gc-sections -Wl,-Bsymbolic-functions -shared -Wl,-soname,libfilamat-jni.so -o java/filamat/libfilamat-jni.so java/filamat/CMakeFiles/filamat-jni.dir/__/__/android/filamat-android/src/main/cpp/MaterialBuilder.cpp.o  -static-libgcc -static-libstdc++  -Wl,-Bstatic  -lc++  -lc++abi  libs/filamat/libfilamat.a  shaders/libshaders.a  libs/filabridge/libfilabridge.a  libs/math/libmath.a  libs/utils/libutils.a  third_party/smol-v/tnt/libsmol-v.a  -Wl,-Bdynamic  -Wl,--start-group  third_party/glslang/tnt/SPIRV/libSPIRV.a  third_party/glslang/tnt/glslang/libglslang.a  third_party/glslang/tnt/OGLCompilersDLL/libOGLCompiler.a  third_party/glslang/tnt/glslang/OSDependent/Unix/libOSDependent.a  -pthread  third_party/glslang/tnt/SPIRV/libSPVRemapper.a  third_party/spirv-tools/source/opt/libSPIRV-Tools-opt.a  third_party/spirv-tools/source/libSPIRV-Tools.a  /usr/lib/x86_64-linux-gnu/librt.so  third_party/spirv-cross/tnt/libspirv-cross-glsl.a  third_party/spirv-cross/tnt/libspirv-cross-msl.a  third_party/spirv-cross/tnt/libspirv-cross-core.a  -static-libgcc -static-libstdc++  -Wl,-Bstatic  -lc++  -lc++abi  -Wl,-Bdynamic  -Wl,--end-group && :
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(new.cpp.o): relocation R_X86_64_32 against symbol `_ZTISt9bad_alloc' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(string.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(charconv.cpp.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(stdexcept.cpp.o): relocation R_X86_64_32S against symbol `_ZTVSt11logic_error' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(algorithm.cpp.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(hash.cpp.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(ios.cpp.o): relocation R_X86_64_32S against symbol `_ZTVNSt3__18ios_baseE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(iostream.cpp.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(locale.cpp.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(memory.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(mutex.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(system_error.cpp.o): relocation R_X86_64_32S against symbol `_ZTVNSt3__114error_categoryE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(vector.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(condition_variable.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(exception.cpp.o): relocation R_X86_64_32S against symbol `_ZTVSt16nested_exception' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(thread.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(future.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[255/304] Linking CXX executable samples/frame_generator
ninja: build stopped: subcommand failed.

```

**Comment by mastergberry** [comment]
For any random people that find this web page on Google like I did looking for a solution with the stuff like @wumo is experiencing:

```
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(new.cpp.o): relocation R_X86_64_32 against symbol `_ZTISt9bad_alloc' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(string.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(charconv.cpp.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(stdexcept.cpp.o): relocation R_X86_64_32S against symbol `_ZTVSt11logic_error' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(algorithm.cpp.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(hash.cpp.o): relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(ios.cpp.o): relocation R_X86_64_32S against symbol `_ZTVNSt3__18ios_baseE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(iostream.cpp.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(locale.cpp.o): relocation R_X86_64_32 against `.bss' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(memory.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(mutex.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(system_error.cpp.o): relocation R_X86_64_32S against symbol `_ZTVNSt3__114error_categoryE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(vector.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(condition_variable.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(exception.cpp.o): relocation R_X86_64_32S against symbol `_ZTVSt16nested_exception' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(thread.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/bin/../lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libc++.a(future.cpp.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
```

The solution is to fix your cmake flags to not include both `-stdlib=libc++` AND `-static-libgcc -static-libstdc++`. These options conflict. If you remove the `-static-libgcc -static-libstdc++` then it will compile/link correctly.
