### ISSUE TITLE
The alpha value of a texture is not seem right.

### ISSUE THREAD

**Issue by minus31** [google/filament#2701]
In filament 1.7.0 release version. When I set `view->setToneMapping(filament::View::ToneMapping::LINEAR)`(figure 1 is the output of this case), a GLB texture of cat's ears are dark but a texture on Mesh(not GLB) seems proper. 

But, when I use the following code which I got from master branch of filament git, 
`filament::ColorGrading* colorGrading = filament::ColorGrading::Builder()
        .toneMapping(filament::ColorGrading::ToneMapping::LINEAR)
        .build(*engine);`
and set `view->setColorGrading(colorGrading)`(figure 2 is the output of this case), The result is vice versa. 

Could anyone can explain this? Thanks in advance. 

**Screenshots**
* **figure 1**

![](https://www.dropbox.com/s/otgpmubstisw8dc/1592313483589.jpg?raw=1)

* **figure 2**

![](https://www.dropbox.com/s/g2tjy15uufzpmb5/1592371703248.jpg?raw=1)

**Comment by romainguy** [comment]
That's expected. Older versions of Filanent were not applying the final linear to sRGB conversion after the tone mapping step. This is now fixed.

**Comment by minus31** [comment]
@romainguy  Thanks for replying. But still the problem seems not solved. Is the older versions of Filament that you mentioned 1.7.0? If it is right, then could you tell me the latest version? Thank you so much.

**Comment by romainguy** [comment]
My point is that the previous behavior was incorrect. The new current behavior is the correct one.

**Comment by minus31** [comment]
@romainguy But the current version of filament's(1.7.0 release) result is left and ear's color is weird but boundary alpha looks fine. To solve ear's color problem, I tried to use another version of filament(Right). Then, I get proper ears color but wrong boundary alpha. I don't know which one is expected one. 

Thanks again

![](https://www.dropbox.com/s/6us3xce0rm5k6jd/Screenshot%202020-06-18%2015.16.09.png?raw=1)
