### ISSUE TITLE
glTF conformance: labels do not appear

### ISSUE THREAD

**Issue by elalish** [google/filament#4576]
Several khronos examples use simple quads with text as labels, but none seem to be showing up in Filament (regression): 
https://modelviewer.dev/fidelity/#khronos-TextureEncodingTest
https://modelviewer.dev/fidelity/#khronos-TextureLinearInterpolationTest
etc.

**Comment by romainguy** [comment]
They do?

<img width="1136" alt="Screen Shot 2021-09-01 at 3 45 17 PM" src="https://user-images.githubusercontent.com/869684/131755156-1a770c78-66aa-4ecb-8d57-28a447960468.png">
<img width="1136" alt="Screen Shot 2021-09-01 at 3 45 37 PM" src="https://user-images.githubusercontent.com/869684/131755160-88751384-9cf3-4e23-beef-d416967c139f.png">

**Comment by romainguy** [comment]
They show up in every glTF file I could test. Including in the web version at https://google.github.io/filament/viewer/:

<img width="623" alt="Screen Shot 2021-09-01 at 3 49 45 PM" src="https://user-images.githubusercontent.com/869684/131755498-d0975d90-28eb-4f7b-a090-09ee9637afbe.png">

Could it be an async loading issue?

**Comment by elalish** [comment]
Maybe? How does one know when your scene has completed rendering in JS? Every other engine does it all during  the first animation frame after loading  the assets, but I'm waiting two and still this happens. Is there an event I should be listening  for?

**Comment by romainguy** [comment]
I don't think it's the rendering that you need to wait for but the loading of assets. But I see you are using `loadResources()` which is synchronous. That's a question for @prideout unfortunately.

**Comment by pixelflinger** [comment]
can we close this?

**Comment by elalish** [comment]
I'm still waiting on an answer for how to fix this when using filament.js. It'd be nice  to keep it open until @prideout or someone can  figure out what's going wrong.

**Comment by prideout** [comment]
@elalish I see that you are now passing a done handler into `loadResources`, does that mean that this has been fixed?

If you were already doing this back in September, then the API isn't working as expected so I need to fix something on my end.

**Comment by elalish** [comment]
It's still a problem as far as I know: https://modelviewer.dev/fidelity/#khronos-TextureEncodingTest

Would you mind updating Filament in our render fidelity test package? I haven't touched it in some time, and you're more likely to figure this out than I.

**Comment by prideout** [comment]
@elalish we have a fix but it won't be available until the weekly release AFTER our next release, so we should probably wait to upgrade the fidelity tests until then.  However we could perhaps cherry-pick this into next week's release cc @bejado

**Comment by elalish** [comment]
It's been broken for half a year; the priority is entirely up to you.
