### ISSUE TITLE
Support Skybox without IBL

### ISSUE THREAD

**Issue by prideout** [google/filament#474]
Apps with default camera exposure and no indirect light will always have a black skybox due to the low DEFAULT_INTENSITY that is used in the absence of an IBL.

Should Filament allow the no-IBL intensity to be configurable?

**Comment by romainguy** [comment]
I'm not sure what you're asking for here. Do you want some kind of default ambient light? Setting the intensity without an IBL currently doesn't make sense since we'd be applying a black IBL anyway. We could provide (or generate at runtime) a white furnace. Not sure how useful that'd be.

**Comment by prideout** [comment]
Currently we create a black default IBL but the skybox shader assumes that the default IBL is a white furnace with a hardcoded intensity of 30000 lux (set [here](https://github.com/google/filament/blob/master/filament/src/View.cpp#L341-L342)).  I'm suggesting that we make this intensity configurable.

**Comment by romainguy** [comment]
No, we rely on the fact that the IBL is black to display nothing. I'm not sure what making the intensity configurable would do since we'll just multiply black by that intensity?

**Comment by prideout** [comment]
Agreed that we should not add any new API for this; it's easy enough for apps to add a tiny IBL to their scene while their full-res IBL is loading in.

Before closing this, I want to point out that the skybox is actually very dark rather than black, which seems weird.  It's due to the fact that the current [skybox shader](https://github.com/google/filament/blob/master/filament/src/materials/skybox.mat) simply looks at the iblLuminance uniform and does not sample from the IBL texture. The default value of iblLuminance is 30000 rather than 0.

**Comment by prideout** [comment]
It samples from the skybox texture, not the IBL texture.  The skybox is dark, not black -- I've proven it by shrinking the camera aperture.  :)

**Comment by romainguy** [comment]
The skybox should be black too. That'd be a bug in how we create the default skybox if it's not.

**Comment by romainguy** [comment]
We should fix the skybox texture and make it black.

**Comment by prideout** [comment]
Fixed by #1298

**Comment by prideout** [comment]
...although we still can't rotate the skybox without an IBL.
