### ISSUE TITLE
Artifacts in windows OpenGL when ibl is rotated.

### ISSUE THREAD

**Issue by thirdmenson** [google/filament#645]
I tried the Suzanne example and by default you are rotating the ibl image, which causes black artifacts all over model which goes away when you rotate. But even when rotating the model you will still see flickering pixel artifacts. This all goes away when I remove the ibl rotation and I get a clean render.  Here is the initial artifact  [image](https://imgur.com/a/lU1q4QG)

btw my graphics card GTX  1080 TI

**Comment by romainguy** [comment]
Thanks. I'm not sure why the rotation would cause this problem as I cannot reproduce the issue on macOS. I wonder if we have a bug in the shader compilation.

@pixelflinger @bejado Could you please take a look? Does it reproduce on our Windows machines?

**Comment by RYDB3RG** [comment]
I can reproduce it too (win, GTX1070). I think colorpass is zfighting with depth pass. Disabling depthpass solves the issue, using color program for depth pass also solves the issue. So it might be `invariant` related.

**Comment by romainguy** [comment]
It's been causing us problems. Does it go away in release builds?

**Comment by RYDB3RG** [comment]
It reproduces also in Release make. Ubuntu 18.10 on same hardware and with nvidia driver works fine.
Removing `invariant` from `generateProlog` seems to also do the trick. Pretty weird.

**Comment by romainguy** [comment]
That's quite unexpected. Maybe we should stop trying to be smart in the depth prepass and just use the material's vertex shader always instead of trying to use the built-in one (the goal was to avoid unnecessary program swaps during the depth prepass since we are sorted by distance).

**Comment by bejado** [comment]
I can't seem to replicate it on Windows or Linux both with Nvidia Quadro M4000s. @RYDB3RG so you're only seeing the issue on Windows?

**Comment by RYDB3RG** [comment]
Yes, only on windows, ubuntu looks good (even with proprietary nvidia drivers)

This is how it looks (artifacts especially around eyes)
[suzanne.mp4](https://www.dropbox.com/s/bf7cb2agetb771y/suzanne%202018-12-18%2008-30-01.mp4?dl=0)

Artifacts completely  disappear when either using color VS for depth pass or removing `invariant` from codegen

Loading monkey.obj with sample_full_pbr also looks good.

**Comment by romainguy** [comment]
Interesting, the artifact is quite different from the usual depth prepass problems we've seen before. We'll have to further investigate…

@RYDB3RG Note that the depth prepass can also disabled per `View` instance in Filament apps.

**Comment by RYDB3RG** [comment]
I changed `beginRenderPass` to make it clear all buffers (`TargetBufferFlags::ALL`)
It looks now a bit more zfight-y [suzanne2.mkv](https://www.dropbox.com/s/ulhnlztn2t9teo2/suzanne%202018-12-20%2009-39-51.mp4?dl=0)
(I think it looked weird before because color wasnt cleared, so the holes were the pixels from the previous frame)

**Comment by romainguy** [comment]
Yeah definitely seems like a depth prepass bug. Still unclear why :/

**Comment by thirdmenson** [comment]
That works !

**Comment by romainguy** [comment]
This should be fixed now.

**Comment by prideout** [comment]
Unfortunately I can still reproduce this issue on my Linux machine with debug builds.

As an experiment, I tried ignoring the depth variant for vertex shaders by hacking getProgramSlow from this line:

uint8_t vertexVariantKey = Variant::filterVariantVertex(variantKey);

to this line:

uint8_t vertexVariantKey = Variant::filterVariantVertex(variantKey) & ~Variant::DEPTH_MASK;

This seems to "fix" the issue, but let me keep investigating; it seems weird that the NVIDIA driver would brazenly ignore the invariant qualifier.
